# Generated by Django 5.0.6 on 2024-06-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_remove_question_choice_type_remove_response_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=models.TextField(default='type the survey description here'),
        ),
    ]
