# Generated by Django 5.0.6 on 2024-06-15 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_alter_response_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='question',
        ),
    ]
