# .github/workflows/deploy-staging.yaml

name: Deploy to Staging

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install -r code/backend/Django/requirements.txt

    - name: Run Tests
      run: |
        echo "Running tests (mock command)"
        # Here you should add the command to run your tests

    - name: Create Release Branch
      if: success()  # Only execute if all previous steps were successful
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git checkout -b release-${{ github.run_number }}
        git push origin release-${{ github.run_number }}

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./code/backend
        file: ./code/backend/Django/Dockerfile
        tags: yourusername/backend:${{ github.sha }}
        push: true