# .github/workflows/deploy-production.yaml

name: Deploy to Production

on:
  push:
    branches:
      - 'release-*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install -r code/backend/Django/requirements.txt

    - name: Run Tests
      run: |
        echo "Running tests (mock command)"
        # Here you should add the command to run your tests

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./code/backend
        file: ./code/backend/Django/Dockerfile
        tags: yourusername/backend:${{ github.sha }}
        push: true

    - name: Deploy
      run: |
        echo "Deploying to production (mock command)"
        # Here you should add the command or script for your deployment