# .github/workflows/deploy-staging.yaml

name: Deploy to Staging

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install -r ./backend/Django/requirements.txt

    - name: Run Tests
      run: |
        python manage.py test --settings=code.backend.Django.base_settings
      env:
        DJANGO_SETTINGS_MODULE: code.backend.Django.base_settings

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./backend
        file: ./backend/Django/Dockerfile
        tags: yourusername/backend:${{ github.sha }}
        push: true

    - name: Create Release Branch
      if: success()  # Only execute if all previous steps were successful
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git branch release-${{ github.run_number }}
        git checkout release-${{ github.run_number }}
        git commit --allow-empty -m "Creating release branch from staging"
        git push origin release-${{ github.run_number }}