# .github/workflows/deploy-production.yaml

name: Deploy to Production

on:
  push:
    branches:
      - 'release/*'  # Trigger on release branches created by staging

jobs:
  deploy-to-production:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Run Migrations
      run: python manage.py migrate
      env:
        DJANGO_SETTINGS_MODULE: backend.Django.settings.production_settings
        DATABASE_URL: ${{ secrets.PRODUCTION_DATABASE_URL }}

    - name: Run Deploy Script
      run: |
        chmod +x deploy_script.sh
        ./deploy_script.sh
      env:
        DJANGO_SETTINGS_MODULE: backend.Django.settings.production_settings
        DATABASE_URL: ${{ secrets.PRODUCTION_DATABASE_URL }}