# .github/workflows/deploy-production.yaml

name: Deploy to Production

on:
  push:
    branches:
      - 'release/*'  # Trigger on release branches created by staging
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy-to-production:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: pip install -r code/backend/Django/requirements.txt

    - name: Run Migrations
      run: python code/backend/Django/manage.py migrate
      env:
        DJANGO_SETTINGS_MODULE: Django.settings.production
        DATABASE_URL: ${{ secrets.PRODUCTION_DATABASE_URL }}

    - name: Set up SSH for deployment
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Execute Deployment Commands via SSH
      run: ssh -o "StrictHostKeyChecking=no" github-actions@github "deploy_script.sh"

