# .github/workflows/deploy-staging.yaml

name: Deploy to Staging

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Build and Push Docker image for Backend
      uses: docker/build-push-action@v2
      with:
        context: ./code/backend
        file: ./code/backend/Dockerfile
        tags: team3rhett/backend-app:staging-${{ github.sha }}
        push: true

    - name: Build and Push Docker image for Frontend
      uses: docker/build-push-action@v2
      with:
        context: ./code/frontend
        file: ./code/frontend/Dockerfile
        tags: team3rhett/frontend-app:staging-${{ github.sha }}
        push: true

  create-release:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: release-${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
        draft: false
        prerelease: false