# .github/workflows/deploy-production.yaml

name: Deploy to Production

on:
  release:
    types: [published]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Build and Push Docker image for Backend
      uses: docker/build-push-action@v2
      with:
        context: ./code/backend
        file: ./code/backend/Dockerfile
        tags: team3rhett/backend-app:release-${{ github.sha }}
        push: true

    - name: Build and Push Docker image for Frontend
      uses: docker/build-push-action@v2
      with:
        context: ./code/frontend
        file: ./code/frontend/Dockerfile
        tags: team3rhett/frontend-app:release-${{ github.sha }}
        push: true