name: ci

on:
  push:
    branches:
      - "main"
      - "staging"

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [staging, production]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up environment variables
        run: echo "DOCKER_ENDPOINT=team3rhett/my-app-${{ matrix.environment }}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: "lab:latest"
          driver: cloud
          endpoint: ${{ env.DOCKER_ENDPOINT }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ${{ matrix.environment == 'staging' && 'team3rhett/my-app-staging:latest' || 'team3rhett/my-app-prod:latest' }}
          outputs: ${{ github.event_name == 'pull_request' && 'type=cacheonly' || 'type=registry,push=true' }}