name: ci

on:
  push:
    branches:
      - "main"
      - "staging"

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [staging, production]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up environment variables
        run: |
          if [ "${{ matrix.environment }}" == "staging" ]; then
            echo "DOCKER_ENDPOINT=team3rhett/my-app-staging" >> $GITHUB_ENV
          else
            echo "DOCKER_ENDPOINT=team3rhett/my-app-prod" >> $GITHUB_ENV
          fi

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Print environment variables for debugging
        run: printenv

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: "latest"
          driver: cloud
          endpoint: ${{ env.DOCKER_ENDPOINT }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ${{ matrix.environment == 'staging' && 'team3rhett/my-app-staging:latest' || 'team3rhett/my-app-prod:latest' }}
          outputs: ${{ github.event_name == 'pull_request' && 'type=cacheonly' || 'type=registry,push=true' }}